# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: example-path

on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: yarn workspace example-npm test:ts
      name: Typescript Tests
    - run: yarn workspace example-npm test:lint
      name: Linting Tests
    - run: yarn workspace example-npm test:jest --coverage
      name: Behavior Tests
    - run: yarn workspace example-npm build
      name: Build
    - uses: codecov/codecov-action@v1
      with:
        flags: example-path
        fail_ci_if_error: true
